name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at every 00:00 KST
    - cron: "0 9 * * *"

jobs:
  update-readme:
    name: Update README.md with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: "True"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_OS: "True"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE: "True"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_PROJECTS: "False"
          SHOW_SHORT_INFO: "False"
          SYMBOL_VERSION: 1
          COMMIT_MESSAGE: "Daily Update of README.md"
